Add GUIButtonPageChangeAdvanced
bluefireoly/KSpigot pull request #16
Opened 2021-03-22 15:34 UTC by NyCodeGHG

Added:
* GuiButtonPageChangeAdvanced (Like the normal one, but with ability to cancel the page change)
* Builder Functions for the above mention functionality

2021-03-26 21:48 UTC, bluefireoly commented
I would add this functionality to the normal gui button instead of adding a completely new kind of button. Dou you see any problems with that approach?

2021-03-27 14:24 UTC, NyCodeGHG commented
No, that would be great

2021-04-29 12:17 UTC, bluefireoly commented
can you add this feature to the default pageChange button? if so, I would definitely merge this PR

2021-04-29 15:25 UTC, NyCodeGHG commented
I will do this as soon as I have found the time.

2021-04-29 18:15 UTC, bluefireoly requested changes
you have to update the builder function as well (does this even compile?)

2021-04-29 18:16 UTC, bluefireoly requested changes

2021-04-29 18:16 UTC, bluefireoly commented on src/main/kotlin/net/axay/kspigot/gui/elements/GUIButtonPageChange.kt
> +    afterChange: ((GUIClickEvent<T>) -> Unit)?
rename to `shouldChange` and `onChange`

2021-04-29 18:31 UTC, NyCodeGHG commented
> you have to update the builder function as well (does this even compile?)

right, there was something

2021-04-29 18:33 UTC, NyCodeGHG commented
Should I create new functions so that the api does not break?

2021-04-29 20:21 UTC, bluefireoly commented
yes, you can create one new function and mark the old one as deprecated, and don't forget to add the `ReplaceWith()` parameter to the deprecated annotation

2021-04-30 12:33 UTC, bluefireoly approved these changes
Thank you!

2021-04-30 12:34 UTC, merged